[project]
name = "helixdb"
queries = "./db/"
container_runtime = "docker"

[local.dev]
port = 6969
build_mode = "dev"

[local.cognee]
port = 6969
build_mode = "dev"

[cloud.boardy.helix]
cluster_id = "1f0d5284-148b-6a99-8764-010203040506"
region = "us-east-1"
build_mode = "dev"

[cloud.boardy.helix.env_vars]